# **1. My First R Program**

In [ ]:
print('Hello World')

[1] "Hello World"

In [ ]:
myString <- ('Hello World')
print(myString)

[1] "Hello World"

# **2. String Variable**

In [ ]:
myString <- ('Hello World')
num <- 10
floatNum <- 0.5
isBool <- TRUE

class(myString)
class(num)
class(floatNum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

# **3. Numerical Operation**

In [ ]:
x <- 5
y <- 3

sum <- x + y
diff <- x - y
mul <- x * y
div <- x / y

print(paste("Sum:", sum))
print(paste("Difference:", diff))
print(paste("Product:", mul))
print(sprintf("Quotient: %.2f", div))


cat("\nSum:", sum, '\n')
cat("Difference:", diff, '\n')
cat("Product:", mul, '\n')
cat("Quotient: %.2f", div, '\n')

[1] "Sum: 8"
[1] "Difference: 2"
[1] "Product: 15"
[1] "Quotient: 1.67"

Sum: 8
Difference: 2
Product: 15
Quotient: %.2f 1.666667

# **4. User Input**

In [ ]:
name = readline("Enter Name: ")
print(paste("Name :", name))

Enter Name: shey
[1] "Name : shey"

# **5. Decision Making**

In [ ]:
grade <- 87

if (grade < 75) {
  print('Failed')
} else {
  print('Passed!')
}

[1] "Passed!"

# **6. Loop**

In [ ]:
for (i in 1:5) {
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

# **7. Functions**

In [ ]:
addNumber <- function(a,b){
  return(a + b)
}

addNumber (2, 3)

[1] 5

# **8. Vectors**

In [ ]:
grades <- c(90, 88, 96, 83, 91)

grades

cat("\nMean:", mean(grades), "\n")
cat("Max:", max(grades), "\n")
cat("Min:", min(grades), "\n")
cat("Sum:", sum(grades), "\n")
cat("Length:", length(grades), "\n")

[1] 90 88 96 83 91

Mean: 89.6
Max: 96
Min: 83
Sum: 448
Length: 5

# **9. Matrices**

In [ ]:
A <- matrix(c(1,2,3,4,5,6),nrow = 3)
A

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

# **10. List**

In [ ]:
student <- list(
  Name = "John Paul",
  Age = 20,
  GPA = 1.25
)

student

$Name
[1] "John Paul"

$Age
[1] 20

$GPA
[1] 1.25

# **11. Data Frames**

In [ ]:
student <- data.frame(
  Name = c("John Paul", "Mer", "Marciano", "Aga", "Aljogs"),
  Age = c(20, 30, 25, 34, 45),
  GPA = c(1.25, 1.5, 1.75, 2.00, 1.6)
)

student

write.csv(student, "student.csv")

  Name      Age GPA
1 John Paul 20  1.25
2 Mer       30  1.50
3 Marciano  25  1.75
4 Aga       34  2.00
5 Aljogs    45  1.60

# **12. Reading Csv Files**

In [ ]:
data <- read.csv("student.csv")
head(data)

summary(data)

  X Name      Age GPA
1 1 John Paul 20  1.25
2 2 Mer       30  1.50
3 3 Marciano  25  1.75
4 4 Aga       34  2.00
5 5 Aljogs    45  1.60

       X            Name        Age            GPA
 Min.   :1   Length   :5   Min.   :20.0   Min.   :1.25
 1st Qu.:2   N.unique :5   1st Qu.:25.0   1st Qu.:1.50
 Median :3   N.blank  :0   Median :30.0   Median :1.60
 Mean   :3   Min.nchar:3   Mean   :30.8   Mean   :1.62
 3rd Qu.:4   Max.nchar:9   3rd Qu.:34.0   3rd Qu.:1.75
 Max.   :5                 Max.   :45.0   Max.   :2.00